---
galaxy_info:
    author: Simon BÃ¤rlocher
    description: Ansible role for installing and configuring Grafana Alloy
    company: Arillso
    license: MIT
    min_ansible_version: "2.14"
    platforms:
        - name: Ubuntu
          versions:
              - focal
              - jammy
              - noble
        - name: Debian
          versions:
              - bullseye
              - bookworm
        - name: EL
          versions:
              - "8"
              - "9"
    galaxy_tags:
        - grafana
        - alloy
        - monitoring
        - observability
        - metrics
        - logs
        - prometheus
        - loki

dependencies: []

collections:
    - ansible.builtin
